
- name: "upgrade packages."
  become: yes
  apt:
    upgrade: "yes"
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
    
- name: Transfer backend files
  copy: 
    src: /root/project/backend
    dest: /home/ubuntu
    force: no
    
- name: Update npm
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm install -g npm@latest
    
- name: intall package dependencies
  become: yes
  shell: |
    cd /home/ubuntu/backend   
    ls -la
    npm install
    npm audit fix --audit-level=critical --force
    
- name: build package
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm run build
    
- name: Run backend
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls
